name: Run unit tests

on:
  push:
    paths:
    - 'test/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-repo
      uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install requirements and run tests
      run: |
        cd test
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python3 -m pytest test_app.py